# Generated by Django 3.1.7 on 2021-05-03 17:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_reg_no', models.CharField(max_length=10)),
                ('patient_name', models.CharField(max_length=65)),
                ('patient_email', models.EmailField(max_length=254)),
                ('patient_mobile', models.CharField(max_length=10)),
                ('admitted_at', models.DateTimeField(default=datetime.datetime(2021, 5, 3, 22, 38, 44, 372873))),
            ],
        ),
    ]
