# Generated by Django 3.1.7 on 2021-05-04 03:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='admitted_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 4, 8, 36, 16, 519388)),
        ),
    ]
