# Generated by Django 3.1.7 on 2021-05-04 03:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_auto_20210504_0836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='patient_mobile',
        ),
        migrations.AlterField(
            model_name='patient',
            name='admitted_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 4, 8, 37, 44, 636544)),
        ),
    ]
