# Generated by Django 3.1.7 on 2021-05-04 03:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_auto_20210504_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='patient_mobile',
            field=models.TextField(default=22, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='admitted_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 4, 8, 40, 13, 145137)),
        ),
    ]
