# Generated by Django 3.1.7 on 2021-05-04 03:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_auto_20210504_0840'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='patient_reg_no',
            new_name='patient_regNo',
        ),
        migrations.AlterField(
            model_name='patient',
            name='admitted_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 4, 9, 0, 16, 685436)),
        ),
    ]
