# Generated by Django 3.1.7 on 2021-05-04 04:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_auto_20210504_0900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='id',
        ),
        migrations.AlterField(
            model_name='patient',
            name='admitted_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 4, 9, 44, 11, 207075)),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_regNo',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
