# Generated by Django 3.1.7 on 2021-05-04 04:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_auto_20210504_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='admitted_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 4, 9, 44, 23, 20272)),
        ),
    ]
